In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("complaints_with_income.csv")

In [4]:
df.shape

(3821055, 19)

In [5]:
df.head()

,unique_key,created_date,closed_date,agency_name,complaint,complaint_detail,complaint_add_detail,zip,city,status,resol_descrip,resol_upd_date,borough,latitude,longitude,median_hh_income,pop,income_category,complaint_group
0,69197623,06/01/2026 02:07:09 PM,06/01/2026 02:16:05 PM,New York City Police Department,Illegal Parking,Blocked Sidewalk,NaN,11103,ASTORIA,Closed,The New York City Police Department responded ...,06/01/2026 02:16:08 PM,QUEENS,40.769581,-73.915593,93324.0,35163,Lower-middle income,parking and vehicles
1,69207017,06/01/2026 02:07:00 PM,06/01/2026 02:07:00 PM,Department of Environmental Protection,Water System,Hydrant Running (WC3),WC3,11209,BROOKLYN,Closed,The Department of Environmental Protection det...,06/01/2026 02:07:00 PM,BROOKLYN,40.624393,-74.038340,93854.0,71004,Lower-middle income,"drainage, water and plumbing"
2,69205534,06/01/2026 02:06:58 PM,06/01/2026 02:06:58 PM,Department of Buildings,Building/Use,No Certificate Of Occupancy/Illegal/Contrary T...,NaN,10456,BRONX,Open,Your Service Request has been submitted to the...,06/01/2026 12:00:00 AM,BRONX,40.833781,-73.913806,34954.0,87533,Lowest income,building/use
3,69198329,06/01/2026 02:06:52 PM,06/01/2026 02:43:43 PM,New York City Police Department,Illegal Parking,Blocked Bike Lane,NaN,11205,BROOKLYN,Closed,The New York City Police Department responded ...,06/01/2026 02:43:47 PM,BROOKLYN,40.697416,-73.956717,93887.0,51676,Lower-middle income,parking and vehicles
4,69196443,06/01/2026 02:06:51 PM,06/01/2026 04:50:30 PM,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,10026,NEW YORK,Closed,The New York City Police Department responded ...,06/01/2026 04:50:33 PM,MANHATTAN,40.802451,-73.946622,81244.0,37123,Lower-middle income,noise

# Cleaning for datawrapper

In [6]:
# I found that there are some zip codes in my dataset that DW says it can't match with / doesn't identify as NYC zip code. I want to check those again here.

invalid_zips = [
    "10279", "10162", "10803", "11021", "11791", "11747", "11580",
    "11735", "11023", "11010", "10704", "11706", "11787", "10710",
    "14068", "12524", "11553", "11575", "10977", "11520", "14845",
    "10523", "11721", "11801", "12180", "11560", "11779", "11788",
    "10970", "11542", "11767", "14223", "11516", "11590", "10591",
    "11552", "12203", "11793", "11733", "11950", "11003", "11570",
    "11727", "10598", "11581", "10573", "11803", "10701"
]

In [7]:
# find me every zip code in my file that is in the invalid zips
df[df["zip"].astype(str).str.zfill(5).isin(invalid_zips)] #convert to string, add padding if needed, and check it is in invalid zips

,unique_key,created_date,closed_date,agency_name,complaint,complaint_detail,complaint_add_detail,zip,city,status,resol_descrip,resol_upd_date,borough,latitude,longitude,median_hh_income,pop,income_category,complaint_group
11011,69189584,05/31/2026 04:33:26 PM,05/31/2026 04:59:03 PM,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,NaN,10279,NEW YORK,Closed,The New York City Police Department responded ...,05/31/2026 04:59:07 PM,MANHATTAN,40.712265,-74.007892,250000.0,259,Highest income,noise
12414,69190494,05/31/2026 01:52:14 PM,05/31/2026 02:13:38 PM,New York City Police Department,Illegal Parking,Posted Parking Sign Violation,NaN,10162,NEW YORK,Closed,The New York City Police Department responded ...,05/31/2026 02:13:42 PM,MANHATTAN,40.769889,-73.950977,114139.0,1603,Upper-middle income,parking and vehicles
14013,69186783,05/31/2026 10:38:45 AM,05/31/2026 04:58:59 PM,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,NaN,10279,NEW YORK,Closed,The New York City Police Department responded ...,05/31/2026 04:59:02 PM,MANHATTAN,40.712265,-74.007892,250000.0,259,Highest income,noise
22834,69179489,05/30/2026 01:47:36 PM,05/30/2026 02:11:26 PM,New York City Police Department,Illegal Parking,Posted Parking Sign Violation,NaN,10162,NEW YORK,Closed,The New York City Police Department responded ...,05/30/2026 02:11:30 PM,MANHATTAN,40.769889,-73.950977,114139.0,1603,Upper-middle income,parking and vehicles
30941,69169203,05/29/2026 06:12:06 PM,05/29/2026 06:38:35 PM,New York City Police Department,Illegal Parking,Posted Parking Sign Violation,NaN,10162,NEW YORK,Closed,The New York City Police Department responded ...,05/29/2026 06:38:38 PM,MANHATTAN,40.769889,-73.950977,114139.0,1603,Upper-middle income,parking and vehicles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3714460,65243944,06/12/2025 10:57:29 AM,07/13/2025 04:01:24 AM,Department of Consumer and Worker Protection,Consumer Complaint,Debt Collection Agency,Harassment,11747,Melville,Closed,The Department of Consumer and Worker Protecti...,07/13/2025 04:01:27 AM,Unspecified,NaN,NaN,159540.0,20513,Highest income,consumer complaint
3731845,65222052,06/10/2025 03:51:43 PM,07/11/2025 04:01:27 AM,Department of Consumer and Worker Protection,Consumer Complaint,Home Improvement Contractor,Installation or Repair Faulty,10701,YONKERS,Closed,The Department of Consumer and Worker Protecti...,07/11/2025 04:01:36 AM,Unspecified,NaN,NaN,64776.0,70676,Lowest income,consumer complaint
3769152,65183882,06/06/2025 05:25:44 PM,06/09/2025 11:56:25 AM,Department of Consumer and Worker Protection,Consumer Complaint,Electronics or Appliance Repair,Goods Damaged or Defective,10710,Yonkers,Closed,The Department of Consumer and Worker Protecti...,06/09/2025 11:56:29 AM,Unspecified,NaN,NaN,108845.0,25855,Upper-middle income,consumer complaint
3801574,65150418,06/03/2025 01:40:49 PM,06/03/2025 03:10:19 PM,New York City Police Department,Illegal Parking,Posted Parking Sign Violation,NaN,10279,NEW YORK,Closed,The Police Department responded and upon arriv...,06/03/2025 03:10:24 PM,MANHATTAN,40.712265,-74.007892,250000.0,259,Highest income,parking and vehicles
3812127,65136133,06/02/2025 11:49:22 AM,08/01/2025 12:05:15 PM,Department of Health and Mental Hygiene,Food Establishment,Letter Grading,Letter Grade Missing/Not Visible,10279,NEW YORK,Closed,The NYC Health Department has responded to you...,08/01/2025 12:05:22 PM,MANHATTAN,40.712265,-74.007892,250000.0,259,Highest income,food establishment

In [8]:
# dropping these values
df = df[
    ~df["zip"].astype(str).str.zfill(5).isin(invalid_zips)
].copy()

In [9]:
#confirming values got dropped
df[df["zip"].astype(str).str.zfill(5).isin(invalid_zips)]

Empty DataFrame
Columns: [unique_key, created_date, closed_date, agency_name, complaint, complaint_detail, complaint_add_detail, zip, city, status, resol_descrip, resol_upd_date, borough, latitude, longitude, median_hh_income, pop, income_category, complaint_group]
Index: []

## Chloropleth map 1: data with zip and complaint counts

In [10]:
df.shape

(3820840, 19)

In [11]:
df

,unique_key,created_date,closed_date,agency_name,complaint,complaint_detail,complaint_add_detail,zip,city,status,resol_descrip,resol_upd_date,borough,latitude,longitude,median_hh_income,pop,income_category,complaint_group
0,69197623,06/01/2026 02:07:09 PM,06/01/2026 02:16:05 PM,New York City Police Department,Illegal Parking,Blocked Sidewalk,NaN,11103,ASTORIA,Closed,The New York City Police Department responded ...,06/01/2026 02:16:08 PM,QUEENS,40.769581,-73.915593,93324.0,35163,Lower-middle income,parking and vehicles
1,69207017,06/01/2026 02:07:00 PM,06/01/2026 02:07:00 PM,Department of Environmental Protection,Water System,Hydrant Running (WC3),WC3,11209,BROOKLYN,Closed,The Department of Environmental Protection det...,06/01/2026 02:07:00 PM,BROOKLYN,40.624393,-74.038340,93854.0,71004,Lower-middle income,"drainage, water and plumbing"
2,69205534,06/01/2026 02:06:58 PM,06/01/2026 02:06:58 PM,Department of Buildings,Building/Use,No Certificate Of Occupancy/Illegal/Contrary T...,NaN,10456,BRONX,Open,Your Service Request has been submitted to the...,06/01/2026 12:00:00 AM,BRONX,40.833781,-73.913806,34954.0,87533,Lowest income,building/use
3,69198329,06/01/2026 02:06:52 PM,06/01/2026 02:43:43 PM,New York City Police Department,Illegal Parking,Blocked Bike Lane,NaN,11205,BROOKLYN,Closed,The New York City Police Department responded ...,06/01/2026 02:43:47 PM,BROOKLYN,40.697416,-73.956717,93887.0,51676,Lower-middle income,parking and vehicles
4,69196443,06/01/2026 02:06:51 PM,06/01/2026 04:50:30 PM,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,10026,NEW YORK,Closed,The New York City Police Department responded ...,06/01/2026 04:50:33 PM,MANHATTAN,40.802451,-73.946622,81244.0,37123,Lower-middle income,noise
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3821050,65129766,06/01/2025 02:07:39 PM,06/01/2025 03:25:37 PM,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,11428,QUEENS VILLAGE,Closed,The Police Department responded to the complai...,06/01/2025 03:25:42 PM,QUEENS,40.726961,-73.737600,91296.0,19028,Lower-middle income,noise
3821051,65127028,06/01/2025 02:07:37 PM,06/01/2025 02:43:03 PM,New York City Police Department,Illegal Parking,Blocked Hydrant,NaN,11207,BROOKLYN,Closed,The Police Department issued a summons in resp...,06/01/2025 02:43:08 PM,BROOKLYN,40.683724,-73.894353,56523.0,93198,Lowest income,parking and vehicles
3821052,65126624,06/01/2025 02:07:30 PM,06/11/2025 07:12:33 AM,Department of Transportation,Bus Stop Shelter Complaint,Broken Glass,NaN,10025,NEW YORK,Closed,The contractor has reported that the requested...,06/11/2025 07:12:37 AM,MANHATTAN,40.802595,-73.964151,108940.0,93065,Upper-middle income,bus stop shelter complaint
3821053,65126778,06/01/2025 02:07:28 PM,06/01/2025 02:16:17 PM,New York City Police Department,Illegal Parking,Parking Permit Improper Use,Parked On Sidewalk,11101,LONG ISLAND CITY,Closed,The Police Department responded to the complai...,06/01/2025 02:16:19 PM,QUEENS,40.743116,-73.956067,121062.0,42219,Upper-middle income,parking and vehicles
3821054,65129356,06/01/2025 02:07:21 PM,06/01/2025 03:50:57 PM,New York City Police Department,Illegal Parking,Blocked Sidewalk,NaN,11420,SOUTH OZONE PARK,Closed,The Police Department issued a summons in resp...,06/01/2025 03:51:03 PM,QUEENS,40.682481,-73.813274,100006.0,49415,Upper-middle income,parking and vehicles

In [12]:
# Creating zip level dataset

df_zip = df.groupby("zip").agg(
    complaint_count=("unique_key", "count"),
    pop=("pop", "first"),
    median_hh_income=("median_hh_income", "first"),
    income_category=("income_category", "first")
).reset_index()

In [13]:
df_zip

       zip  complaint_count    pop  median_hh_income      income_category
0    10001            20837  30511          129852.0       Highest income
1    10002            31094  76873           48386.0        Lowest income
2    10003            27330  53560          154262.0       Highest income
3    10004             5991   3711          250000.0       Highest income
4    10005             3596   9439          190233.0       Highest income
..     ...              ...    ...               ...                  ...
177  11691            20743  69359           56135.0        Lowest income
178  11692             5908  22734           49720.0        Lowest income
179  11693             4798  13244           68449.0        Lowest income
180  11694             8202  21489          111011.0  Upper-middle income
181  11697              234   4429          122667.0  Upper-middle income

[182 rows x 5 columns]

In [14]:
# creating complaints per 100K column 

df_zip["complaints_per_100k"] = (
    df_zip["complaint_count"] / df_zip["pop"] * 100000
)

In [15]:
# converting complaint column to whole numbers 
df_zip["complaints_per_100k"] = df_zip["complaints_per_100k"].round().astype(int)

In [16]:
df_zip

,zip,complaint_count,pop,median_hh_income,income_category,complaints_per_100k
0,10001,20837,30511,129852.0,Highest income,68293
1,10002,31094,76873,48386.0,Lowest income,40449
2,10003,27330,53560,154262.0,Highest income,51027
3,10004,5991,3711,250000.0,Highest income,161439
4,10005,3596,9439,190233.0,Highest income,38097
...,...,...,...,...,...,...
177,11691,20743,69359,56135.0,Lowest income,29907
178,11692,5908,22734,49720.0,Lowest income,25988
179,11693,4798,13244,68449.0,Lowest income,36228
180,11694,8202,21489,111011.0,Upper-middle income,38168
181,11697,234,4429,122667.0,Upper-middle income,5283

In [17]:
(df_zip["complaints_per_100k"] < 40000).value_counts(normalize=True) * 100

complaints_per_100k
False    53.296703
True     46.703297
Name: proportion, dtype: float64

In [18]:
# saving dataset 
df_zip.to_csv("complaintsper100k_by_zip.csv", index=False)

## Chloropleth map 2: with only top complaints

In [19]:
# calculating 90th percentile for complaints per 100k to put into datawrapper
df_zip["complaints_per_100k"].quantile(0.9)

np.float64(67846.9)

## Bar graph 1: median complaints per 100k by income category

In [20]:
df_zip["complaints_per_100k"] = df_zip["complaints_per_100k"].round().astype(int)

In [21]:
df_complaints_by_income = (
    df_zip
    .groupby("income_category", as_index=False)["complaints_per_100k"]
    .median()
)

In [22]:
df_complaints_by_income

       income_category  complaints_per_100k
0       Highest income              41632.5
1  Lower-middle income              41543.0
2        Lowest income              44269.0
3  Upper-middle income              31268.0

In [23]:
# saving dataset 
df_complaints_by_income.to_csv("bar_graph_complaints_by_income.csv", index=False)

## Table 1: Top complaint categories

In [24]:
df

,unique_key,created_date,closed_date,agency_name,complaint,complaint_detail,complaint_add_detail,zip,city,status,resol_descrip,resol_upd_date,borough,latitude,longitude,median_hh_income,pop,income_category,complaint_group
0,69197623,06/01/2026 02:07:09 PM,06/01/2026 02:16:05 PM,New York City Police Department,Illegal Parking,Blocked Sidewalk,NaN,11103,ASTORIA,Closed,The New York City Police Department responded ...,06/01/2026 02:16:08 PM,QUEENS,40.769581,-73.915593,93324.0,35163,Lower-middle income,parking and vehicles
1,69207017,06/01/2026 02:07:00 PM,06/01/2026 02:07:00 PM,Department of Environmental Protection,Water System,Hydrant Running (WC3),WC3,11209,BROOKLYN,Closed,The Department of Environmental Protection det...,06/01/2026 02:07:00 PM,BROOKLYN,40.624393,-74.038340,93854.0,71004,Lower-middle income,"drainage, water and plumbing"
2,69205534,06/01/2026 02:06:58 PM,06/01/2026 02:06:58 PM,Department of Buildings,Building/Use,No Certificate Of Occupancy/Illegal/Contrary T...,NaN,10456,BRONX,Open,Your Service Request has been submitted to the...,06/01/2026 12:00:00 AM,BRONX,40.833781,-73.913806,34954.0,87533,Lowest income,building/use
3,69198329,06/01/2026 02:06:52 PM,06/01/2026 02:43:43 PM,New York City Police Department,Illegal Parking,Blocked Bike Lane,NaN,11205,BROOKLYN,Closed,The New York City Police Department responded ...,06/01/2026 02:43:47 PM,BROOKLYN,40.697416,-73.956717,93887.0,51676,Lower-middle income,parking and vehicles
4,69196443,06/01/2026 02:06:51 PM,06/01/2026 04:50:30 PM,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,10026,NEW YORK,Closed,The New York City Police Department responded ...,06/01/2026 04:50:33 PM,MANHATTAN,40.802451,-73.946622,81244.0,37123,Lower-middle income,noise
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3821050,65129766,06/01/2025 02:07:39 PM,06/01/2025 03:25:37 PM,New York City Police Department,Noise - Residential,Loud Music/Party,NaN,11428,QUEENS VILLAGE,Closed,The Police Department responded to the complai...,06/01/2025 03:25:42 PM,QUEENS,40.726961,-73.737600,91296.0,19028,Lower-middle income,noise
3821051,65127028,06/01/2025 02:07:37 PM,06/01/2025 02:43:03 PM,New York City Police Department,Illegal Parking,Blocked Hydrant,NaN,11207,BROOKLYN,Closed,The Police Department issued a summons in resp...,06/01/2025 02:43:08 PM,BROOKLYN,40.683724,-73.894353,56523.0,93198,Lowest income,parking and vehicles
3821052,65126624,06/01/2025 02:07:30 PM,06/11/2025 07:12:33 AM,Department of Transportation,Bus Stop Shelter Complaint,Broken Glass,NaN,10025,NEW YORK,Closed,The contractor has reported that the requested...,06/11/2025 07:12:37 AM,MANHATTAN,40.802595,-73.964151,108940.0,93065,Upper-middle income,bus stop shelter complaint
3821053,65126778,06/01/2025 02:07:28 PM,06/01/2025 02:16:17 PM,New York City Police Department,Illegal Parking,Parking Permit Improper Use,Parked On Sidewalk,11101,LONG ISLAND CITY,Closed,The Police Department responded to the complai...,06/01/2025 02:16:19 PM,QUEENS,40.743116,-73.956067,121062.0,42219,Upper-middle income,parking and vehicles
3821054,65129356,06/01/2025 02:07:21 PM,06/01/2025 03:50:57 PM,New York City Police Department,Illegal Parking,Blocked Sidewalk,NaN,11420,SOUTH OZONE PARK,Closed,The Police Department issued a summons in resp...,06/01/2025 03:51:03 PM,QUEENS,40.682481,-73.813274,100006.0,49415,Upper-middle income,parking and vehicles

In [25]:
df['complaint_group'].value_counts().head(10)

complaint_group
parking and vehicles              891055
noise                             771604
drainage, water and plumbing      593380
dirty or unsanitary conditions    268746
street condition                  104855
paint/plaster                      64132
snow or ice                        63690
traffic signal condition           51338
door/window                        49883
encampment                         45316
Name: count, dtype: int64

## Bargraph2: Top complaint categories for high income group

In [26]:
complaint_by_income = (
    df
    .groupby("income_category")["complaint_group"]
    .value_counts(normalize=True)
    .mul(100)
    .reset_index(name="percent")
)

complaint_by_income.head(20)

   income_category                 complaint_group    percent
0   Highest income                           noise  18.225685
1   Highest income            parking and vehicles  17.662799
2   Highest income    drainage, water and plumbing   8.658615
3   Highest income                      encampment   5.461016
4   Highest income  dirty or unsanitary conditions   5.388577
5   Highest income      homeless person assistance   3.241538
6   Highest income              vendor enforcement   3.154057
7   Highest income                street condition   3.013336
8   Highest income              noise - helicopter   2.516952
9   Highest income      for hire vehicle complaint   1.932493
10  Highest income        traffic signal condition   1.624925
11  Highest income                     snow or ice   1.267085
12  Highest income   general construction/plumbing   1.186136
13  Highest income                   drug activity   1.145958
14  Highest income         maintenance or facility   1.049373
15  Highest income                         traffic   0.988216
16  Highest income     non-emergency police matter   0.952986
17  Highest income              sidewalk condition   0.879360
18  Highest income                          rodent   0.842547
19  Highest income                  taxi complaint   0.830275

In [27]:
top10 = (
    complaint_by_income
    .groupby("income_category")
    .head(10)
)

top10

         income_category                 complaint_group    percent
0         Highest income                           noise  18.225685
1         Highest income            parking and vehicles  17.662799
2         Highest income    drainage, water and plumbing   8.658615
3         Highest income                      encampment   5.461016
4         Highest income  dirty or unsanitary conditions   5.388577
5         Highest income      homeless person assistance   3.241538
6         Highest income              vendor enforcement   3.154057
7         Highest income                street condition   3.013336
8         Highest income              noise - helicopter   2.516952
9         Highest income      for hire vehicle complaint   1.932493
159  Lower-middle income            parking and vehicles  30.127325
160  Lower-middle income                           noise  17.019938
161  Lower-middle income    drainage, water and plumbing  14.528471
162  Lower-middle income  dirty or unsanitary conditions   7.038959
163  Lower-middle income                street condition   3.126305
164  Lower-middle income                     snow or ice   2.026212
165  Lower-middle income                   paint/plaster   1.429763
166  Lower-middle income        traffic signal condition   1.393723
167  Lower-middle income                    damaged tree   1.121227
168  Lower-middle income                     door/window   1.069770
315        Lowest income                           noise  24.243102
316        Lowest income            parking and vehicles  19.831805
317        Lowest income    drainage, water and plumbing  19.670714
318        Lowest income  dirty or unsanitary conditions   7.546622
319        Lowest income                   paint/plaster   2.384526
320        Lowest income                     door/window   1.815257
321        Lowest income                street condition   1.759809
322        Lowest income                         general   1.306009
323        Lowest income                        electric   1.153783
324        Lowest income        traffic signal condition   1.115331
476  Upper-middle income            parking and vehicles  27.517745
477  Upper-middle income                           noise  14.769262
478  Upper-middle income    drainage, water and plumbing  10.432878
479  Upper-middle income  dirty or unsanitary conditions   6.887886
480  Upper-middle income                street condition   4.927099
481  Upper-middle income                     snow or ice   3.335286
482  Upper-middle income                    damaged tree   1.793555
483  Upper-middle income        traffic signal condition   1.720821
484  Upper-middle income          street light condition   1.377683
485  Upper-middle income   general construction/plumbing   1.310082